/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "dashboard.index": [],
    "home": [],
    "about": [],
    "safety": [],
    "support": [],
    "careers": [],
    "user.register": [],
    "user.login": []
}
}
export {};
